name: Terraform Plan

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  Terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws_access_key_id: ${{AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{AWS_SECRET_ACCESS_KEY}}
          region: us-east-1

      - name: Terraform setup
        uses: hashicorp/terraform-setup@v2

      - name: Terraform initialize
        run:  terraform init

      - name: Terraform validate
        run: terraform validate

      - name: terraform Plan
        run: terraform plan -out=tfplan      

      - name: Terraform Apply
        run: terraform apply -auto-approve  