name: Terraform Plan

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      runner:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SSH_PRIVATE_KEY:
        required: false
      SSH_PUBLIC_KEY:
        required: false
      TF_VAR_DOCKER_USERNAME:
        required: false   
      TF_VAR_DOCKER_PASSWORD:
        required: false  
    

jobs:
  terraform_plan:
    runs-on: ${{inputs.runner}}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup ssh keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          ssh-keyscan github.com >> ~/.ssh/known_hosts         

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}      
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1        

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init  -reconfigure

      - name: Select Terraform Workspace
        run: terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}

      - name: Planned terraform changes
        run:  terraform plan      

      - name: Apply changes to production
        run:  terraform apply -auto-approve  